#
default: &default
 adapter: postgresql
 encoding: UTF8
 pool: 5
 timeout: 5000

development:
 <<: *default
 database: db/listr_development
 host: localhost
 username: tigranas
 password: Virl645830

test:
 <<: *default
 database: db/listr_test
 host: localhost
 username: tigranas
 password: Virl645830

production:
 <<: *default
 database: db/listr_production
 host: localhost
 username: tigranas
 password: Virl645830
